// Demo data and reusable UI components
const rooms=[['Ночной сеанс','🎬','p2','6 друзей'],['Космическая пауза','🪐','p3','12 зрителей'],['Смешные находки','😂','', '8 друзей']];
let state={screen:'welcome',playing:false,privacy:'public',theme:'dark',messages:[['Лина','Это было красиво! ✨',false],['Ты','Согласен, какой кадр 😮',true],['Илья','🍿🍿🍿',false]]};
const app=document.querySelector('#app');
const icon={home:'⌂',search:'⌕',create:'＋',rooms:'◈',profile:'☺'};
function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function avatar(e='🙂'){return `<div class="avatar">${e}</div>`}
function bottom(active=state.screen){if(active==='welcome'||active==='room')return '';return `<nav class="bottom">${[['home','Главная'],['search','Поиск'],['create','Создать'],['rooms','Комнаты'],['profile','Профиль']].map(([id,n])=>`<button class="nav ${active===id?'active':''}" onclick="go('${id}')"><i>${icon[id]}</i>${n}</button>`).join('')}</nav>`}
function roomCard(r){return `<article class="room-card"><div class="poster ${r[2]}"><span class="badge">${r[1]} LIVE</span></div><div class="room-info"><b>${r[0]}</b><small>👤 ${r[3]} · в сети 🟢</small><button class="join" onclick="go('room')">Войти</button></div></article>`}
function home(){return `<section class="screen"><header class="top"><div class="user">${avatar('🧑‍🎤')}<div><b>Привет, Луна!</b><div class="online">В сети 🟢</div></div></div><button class="icon" onclick="toast('Новых уведомлений нет')">♧</button></header><article class="hero"><h2>Начать просмотр вместе</h2><p>Собери друзей в одной комнате и включай что угодно.</p><div class="hero-actions"><button onclick="go('create')">Создать комнату</button><button onclick="joinCode()">По коду</button></div></article>${section('Активные комнаты друзей',rooms)}${section('Популярно сейчас',rooms.slice().reverse())}</section>${bottom('home')}`}
function section(t,list){return `<div class="section"><div class="section-title"><h3>${t}</h3><span>Все</span></div><div class="rail">${list.map(roomCard).join('')}</div></div>`}
function welcome(){return `<section class="screen welcome"><div class="orb a"></div><div class="orb b"></div><div class="orb c"></div><span class="femoji e1">🎬</span><span class="femoji e2">✨</span><span class="femoji e3">🎧</span><div class="brand">◉</div><h1>Смотри. Чувствуй.<br>Будь рядом.</h1><p>Твоё уютное место для фильмов, сериалов и вечеров с друзьями — даже на расстоянии.</p><button class="btn" onclick="go('home')">Войти</button><button class="btn secondary" onclick="go('home')">Продолжить как гость</button></section>`}
function create(){return `<section class="screen"><header class="headrow"><button class="back" onclick="go('home')">‹</button><h2>Новая комната</h2></header><div class="field"><label>Название комнаты</label><input class="input" id="roomName" value="Вечер кино у Луны 🍿"></div><div class="field"><label>Описание</label><textarea>Смотрим что-то красивое и болтаем</textarea></div><div class="field"><label>Тема комнаты</label><div class="chips">${['🎬 Кино','😂 Мемы','🎮 Игры','🎵 Музыка','📺 Сериалы','👻 Ужасы','❤️ Друзья'].map((x,i)=>`<button class="chip ${i===0?'selected':''}" onclick="selectChip(this)">${x}</button>`).join('')}</div></div><div class="field"><label>Обложка</label><div class="poster p2" style="height:106px;border-radius:15px;align-items:center;justify-content:center">＋ Загрузить обложку</div></div><div class="field"><label>Приватность</label><div class="privacy"><button class="selected" onclick="privacy(this,'public')">🌐 Публичная</button><button onclick="privacy(this,'private')">🔒 Приватная</button></div></div><div class="field"><label>Ссылка на видео</label><input class="input" placeholder="https://..."></div><div class="switchrow">Разрешить гостям управлять плеером <button class="switch" onclick="this.classList.toggle('off')"></button></div><button class="btn" onclick="createRoom()">Создать комнату</button></section>${bottom('create')}`}
function room(){return `<section class="screen"><header class="headrow"><button class="back" onclick="go('home')">‹</button><h2>Ночной сеанс <small class="online">●</small></h2><button class="icon" onclick="copyCode()">⌘</button><button class="icon" onclick="openPeople()">☷</button></header><div class="player"><div class="video"><button class="playbig" onclick="togglePlay()">${state.playing?'Ⅱ':'▶'}</button><span class="sync">✓ Синхронизировано ✨</span></div><div class="controls"><div class="progress" onclick="progress(this,event)"><span></span></div><div class="controlrow"><button onclick="toast('−10 секунд')">↶</button><button onclick="togglePlay()">${state.playing?'Ⅱ':'▶'}</button><button onclick="toast('+10 секунд')">↷</button><span>18:24 / 52:10</span><button>♬</button><button onclick="toast('Качество: 1080p')">HD</button></div></div></div><div class="people">${['🧑‍🎤','🧑‍🚀','👩🏻‍🦰','🧔'].map((x,i)=>`<div class="person">${avatar(x)}<i class="dot"></i></div>`).join('')}<button onclick="openPeople()">4 участника ›</button></div><div class="section-title"><h3>Чат комнаты</h3><span>💬 онлайн</span></div><div class="chat">${state.messages.map((m,i)=>`<div class="message ${m[2]?'owner':''}">${avatar(m[2]?'🧑‍🎤':i?'🧑‍🚀':'👩🏻‍🦰')}<div><div class="tiny">${m[0]} · сейчас</div><div class="bubble">${m[1]}</div></div></div>`).join('')}<div class="sys">Алекс присоединился к комнате</div></div><div class="chat-input"><input class="input" id="chatText" placeholder="Сообщение…" onkeydown="if(event.key==='Enter')sendMessage()"><button class="round" onclick="react('😂')">☺</button><button class="round" onclick="sendMessage()">➤</button></div><div class="chips">${['😂','❤️','😱','🔥','👏','😭','🍿'].map(x=>`<button class="chip" onclick="react('${x}')">${x}</button>`).join('')}</div></section>`}
function search(){let media=['Лунный путь','Параллели','Громче тишины','После полуночи'];return `<section class="screen"><h2>Найти что посмотреть</h2><div class="search"><input class="input" placeholder="Фильмы, видео, музыка…" oninput="toast('Ищем: '+this.value)"><button class="icon">⌕</button></div><div class="chips">${['Фильмы','Сериалы','Видео','Музыка','Эфиры'].map((x,i)=>`<button class="chip ${i===0?'selected':''}" onclick="selectChip(this)">${x}</button>`).join('')}</div><div class="grid section">${media.map((x,i)=>`<article class="media" onclick="mediaInfo('${x}')"><div class="poster p${i%3+1}"><span class="badge">${i%2?'1:48:00':'2:14:00'}</span></div><b>${x}</b></article>`).join('')}</div></section>${bottom('search')}`}
function profile(){return `<section class="screen profile">${avatar('🧑‍🎤')}<h2>Луна Власова</h2><p>Люблю хорошие кадры и плохие шутки ✨</p><button class="btn secondary" onclick="toast('Режим редактирования включён')">Редактировать профиль</button><div class="stats"><div><b>42</b><span>друга</span></div><div><b>18</b><span>комнат</span></div><div><b>126 ч</b><span>вместе</span></div></div><div class="section-title"><h3>Настройки</h3></div>${['Тема интерфейса','Язык','Уведомления','Приватность','Качество видео','Автозапуск'].map((x,i)=>`<div class="setting"><span>${x}</span>${i===0?`<button class="chip" onclick="toggleTheme()">${state.theme==='dark'?'Тёмная':'Светлая'}</button>`:'<span class="tiny">›</span>'}</div>`).join('')}<div class="setting" style="color:#ff91bb">Выйти из аккаунта <span>›</span></div></section>${bottom('profile')}`}
function roomsScreen(){return `<section class="screen"><h2>Мои комнаты</h2>${section('Сейчас смотрим',rooms)}${section('Недавние просмотры',rooms.slice(1))}</section>${bottom('rooms')}`}
function render(){let views={welcome,home,create,room,search,profile,rooms:roomsScreen};app.innerHTML=views[state.screen]();app.scrollTop=0}
function go(s){state.screen=s;render()}
function selectChip(el){el.parentNode.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function privacy(el,p){el.parentNode.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');state.privacy=p}
function createRoom(){toast('Комната создана ✨');state.screen='room';render()}
function joinCode(){let c=prompt('Введите код комнаты');if(c)go('room')}
function copyCode(){navigator.clipboard?.writeText('PULSE-84K');toast('Код PULSE-84K скопирован')}
function togglePlay(){state.playing=!state.playing;render();toast(state.playing?'Воспроизведение':'На паузе')}
function progress(el,e){el.querySelector('span').style.width=(e.offsetX/el.clientWidth*100)+'%'}
function sendMessage(){let i=document.querySelector('#chatText'),v=i?.value.trim();if(v){state.messages.push(['Ты',v,true]);render()}}
function react(x){let e=document.createElement('span');e.className='reaction';e.textContent=x;e.style.left=(30+Math.random()*55)+'%';e.style.bottom='75px';app.append(e);toast(x+' отправлено')}
function openPeople(){app.insertAdjacentHTML('beforeend',`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="sheet-card"><div class="headrow"><h2>Участники · 4</h2><button class="back" onclick="this.closest('.modal').remove()">×</button></div>${[['Луна','Ведущая 👑','🧑‍🎤'],['Маша','Смотрит','👩🏻‍🦰'],['Алекс','Печатает…','🧑‍🚀'],['Илья','Отошёл','🧔']].map((p,i)=>`<div class="setting">${avatar(p[2])}<div style="flex:1;margin-left:10px"><b>${p[0]}</b><div class="tiny">${p[1]} · 🟢</div></div>${i?'<button class="chip" onclick="this.textContent=\'🔇\'">♬</button>':''}</div>`).join('')}</div></div>`)}
function mediaInfo(n){app.insertAdjacentHTML('beforeend',`<div class="modal" onclick="if(event.target===this)this.remove()"><div class="modal-card"><div class="poster p2" style="height:150px;border-radius:18px;margin-bottom:16px"></div><h2>${n}</h2><p>Демонстрационная карточка контента. Пригласи друзей и начните синхронный просмотр.</p><button class="btn" onclick="this.closest('.modal').remove();go('create')">Смотреть вместе</button></div></div>`)}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('light');render()}
render();
