# Generated by Codex on 2026-07-26
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchparty", "0006_friendrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name="room", name="duration_seconds", field=models.FloatField(default=0)),
        migrations.AddField(model_name="room", name="genres", field=models.JSONField(blank=True, default=list)),
        migrations.CreateModel(
            name="ViewingActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_seconds", models.PositiveIntegerField(default=0)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("longest_movie_seconds", models.PositiveIntegerField(default=0)),
                ("genre_counts", models.JSONField(blank=True, default=dict)),
                ("daily_seconds", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="viewing_activity", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
