# Generated by Codex on 2026-07-29
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchparty", "0007_room_viewingactivity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanionActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seconds", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("companion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="companion_of_activity", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="companion_activity", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="companionactivity",
            constraint=models.UniqueConstraint(fields=("user", "companion"), name="unique_user_companion_activity"),
        ),
        migrations.AddConstraint(
            model_name="companionactivity",
            constraint=models.CheckConstraint(condition=~models.Q(user=models.F("companion")), name="companion_activity_not_self"),
        ),
    ]
