# Generated by Codex on 2026-07-30
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_mutes(apps, schema_editor):
    RoomMember = apps.get_model("watchparty", "RoomMember")
    RoomMute = apps.get_model("watchparty", "RoomMute")
    for member in RoomMember.objects.filter(is_muted=True).iterator():
        RoomMute.objects.get_or_create(room_id=member.room_id, user_id=member.user_id)


class Migration(migrations.Migration):
    dependencies = [
        ("watchparty", "0009_roomban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomMute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("muted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="issued_room_mutes", to=settings.AUTH_USER_MODEL)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mutes", to="watchparty.room")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="room_mutes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="roommute",
            constraint=models.UniqueConstraint(fields=("room", "user"), name="unique_room_mute"),
        ),
        migrations.RunPython(preserve_existing_mutes, migrations.RunPython.noop),
    ]
