# Generated by Codex on 2026-07-30
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("watchparty", "0010_roommute")]

    operations = [
        migrations.AddField(
            model_name="room",
            name="uploaded_video",
            field=models.FileField(blank=True, null=True, upload_to="room-videos/%Y/%m/"),
        ),
    ]
