from django.urls import path
from .views import RoomDetailView, RoomListCreateView, account_login, activity, app_presence, demo_login, friend_requests, friends, invite_room_friends, join_room, moderate_member, profile, public_user_profile, public_user_watch_preview, register, respond_room_invitation, room_invitations, room_members, room_messages, room_messages_batch, room_snapshot, room_stream, room_uploaded_media, room_upload_video, username_available, telegram_sticker_packs, telegram_sticker_file

urlpatterns = [
    path("auth/demo-login/", demo_login),
    path("auth/register/", register),
    path("auth/login/", account_login),
    path("auth/username-available/", username_available),
    path("profile/", profile),
    path("presence/", app_presence),
    path("users/<int:user_id>/profile/", public_user_profile),
    path("users/<int:user_id>/watch-preview/", public_user_watch_preview),
    path("activity/", activity),
    path("friends/", friends),
    path("friends/requests/", friend_requests),
    path("sticker-packs/", telegram_sticker_packs),
    path("stickers/<int:sticker_id>/file/", telegram_sticker_file),
    path("stickers/<int:sticker_id>/preview/", lambda request, sticker_id: telegram_sticker_file(request, sticker_id, preview=True)),
    path("room-invitations/", room_invitations),
    path("room-invitations/<int:invitation_id>/", respond_room_invitation),
    path("rooms/", RoomListCreateView.as_view()),
    path("rooms/join/", join_room),
    path("rooms/<int:room_id>/members/", room_members),
    path("rooms/<int:room_id>/snapshot/", room_snapshot),
    path("rooms/<int:room_id>/invites/", invite_room_friends),
    path("rooms/<int:room_id>/members/<int:user_id>/moderate/", moderate_member),
    path("rooms/<int:room_id>/stream/", room_stream),
    path("rooms/<int:room_id>/upload/", room_upload_video),
    path("rooms/<int:room_id>/media/", room_uploaded_media),
    path("rooms/<int:room_id>/messages/batch/", room_messages_batch),
    path("rooms/<int:room_id>/messages/", room_messages),
    path("rooms/<int:pk>/", RoomDetailView.as_view()),
]
